name: Publish

on:
  release:
    types:
      - [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: author/action-publish@stable
        env:
          REGISTRY_TOKEN: "${{ secrets.NPM_TOKEN }}"
